// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feeds.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, url, title, site_url) VALUES ($1, $2, $3, $4) RETURNING id, user_id, url, title, site_url, last_polled_at, last_status, created_at, etag, last_modified, next_poll_at, poll_interval_minutes
`

type CreateFeedParams struct {
	UserID  uuid.UUID
	Url     string
	Title   string
	SiteUrl string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, createFeed,
		arg.UserID,
		arg.Url,
		arg.Title,
		arg.SiteUrl,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.SiteUrl,
		&i.LastPolledAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.Etag,
		&i.LastModified,
		&i.NextPollAt,
		&i.PollIntervalMinutes,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :execrows
DELETE FROM feeds WHERE user_id = $1 AND id = $2
`

type DeleteFeedParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteFeed(ctx context.Context, arg DeleteFeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeed, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFeed = `-- name: GetFeed :one
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at, etag, last_modified, next_poll_at, poll_interval_minutes FROM feeds WHERE user_id = $1 AND id = $2
`

type GetFeedParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) (Feed, error) {
	row := q.db.QueryRow(ctx, getFeed, arg.UserID, arg.ID)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Url,
		&i.Title,
		&i.SiteUrl,
		&i.LastPolledAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.Etag,
		&i.LastModified,
		&i.NextPollAt,
		&i.PollIntervalMinutes,
	)
	return i, err
}

const keepFeedItems = `-- name: KeepFeedItems :execrows
UPDATE items SET kept_at = now(), updated_at = now()
WHERE user_id = $1 AND feed_id = $2 AND kept_at IS NULL
`

type KeepFeedItemsParams struct {
	UserID uuid.UUID
	FeedID pgtype.UUID
}

// Unsubscribing keeps the feed's items in the library: stamp everything
// still unkept so the Mind predicate keeps showing them once feed_id nulls.
func (q *Queries) KeepFeedItems(ctx context.Context, arg KeepFeedItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, keepFeedItems, arg.UserID, arg.FeedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at, etag, last_modified, next_poll_at, poll_interval_minutes FROM feeds WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListFeeds(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.SiteUrl,
			&i.LastPolledAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.Etag,
			&i.LastModified,
			&i.NextPollAt,
			&i.PollIntervalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsDueForPoll = `-- name: ListFeedsDueForPoll :many
SELECT id, user_id, url, title, site_url, last_polled_at, last_status, created_at, etag, last_modified, next_poll_at, poll_interval_minutes FROM feeds WHERE next_poll_at <= now() ORDER BY next_poll_at ASC
`

// Cross-user by design (system-wide poller). Only feeds whose adaptive
// schedule has come due; items saved remain scoped to each feed's user_id.
func (q *Queries) ListFeedsDueForPoll(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.Query(ctx, listFeedsDueForPoll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Url,
			&i.Title,
			&i.SiteUrl,
			&i.LastPolledAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.Etag,
			&i.LastModified,
			&i.NextPollAt,
			&i.PollIntervalMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFeedPolled = `-- name: SetFeedPolled :exec
UPDATE feeds SET last_polled_at = $3, last_status = $4, etag = $5, last_modified = $6,
  next_poll_at = $7, poll_interval_minutes = $8
WHERE user_id = $1 AND id = $2
`

type SetFeedPolledParams struct {
	UserID              uuid.UUID
	ID                  uuid.UUID
	LastPolledAt        pgtype.Timestamptz
	LastStatus          string
	Etag                string
	LastModified        string
	NextPollAt          pgtype.Timestamptz
	PollIntervalMinutes int32
}

func (q *Queries) SetFeedPolled(ctx context.Context, arg SetFeedPolledParams) error {
	_, err := q.db.Exec(ctx, setFeedPolled,
		arg.UserID,
		arg.ID,
		arg.LastPolledAt,
		arg.LastStatus,
		arg.Etag,
		arg.LastModified,
		arg.NextPollAt,
		arg.PollIntervalMinutes,
	)
	return err
}
