// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: highlights.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createHighlight = `-- name: CreateHighlight :one
INSERT INTO highlights (user_id, source_item_id, quote_item_id, exact, prefix, suffix, offset_hint)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, source_item_id, quote_item_id, exact, prefix, suffix, offset_hint, created_at
`

type CreateHighlightParams struct {
	UserID       uuid.UUID
	SourceItemID uuid.UUID
	QuoteItemID  uuid.UUID
	Exact        string
	Prefix       string
	Suffix       string
	OffsetHint   int32
}

func (q *Queries) CreateHighlight(ctx context.Context, arg CreateHighlightParams) (Highlight, error) {
	row := q.db.QueryRow(ctx, createHighlight,
		arg.UserID,
		arg.SourceItemID,
		arg.QuoteItemID,
		arg.Exact,
		arg.Prefix,
		arg.Suffix,
		arg.OffsetHint,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceItemID,
		&i.QuoteItemID,
		&i.Exact,
		&i.Prefix,
		&i.Suffix,
		&i.OffsetHint,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHighlight = `-- name: DeleteHighlight :execrows
DELETE FROM highlights WHERE user_id = $1 AND id = $2
`

type DeleteHighlightParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHighlight, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHighlight = `-- name: GetHighlight :one
SELECT id, user_id, source_item_id, quote_item_id, exact, prefix, suffix, offset_hint, created_at FROM highlights WHERE user_id = $1 AND id = $2
`

type GetHighlightParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetHighlight(ctx context.Context, arg GetHighlightParams) (Highlight, error) {
	row := q.db.QueryRow(ctx, getHighlight, arg.UserID, arg.ID)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceItemID,
		&i.QuoteItemID,
		&i.Exact,
		&i.Prefix,
		&i.Suffix,
		&i.OffsetHint,
		&i.CreatedAt,
	)
	return i, err
}

const listHighlightsBySource = `-- name: ListHighlightsBySource :many
SELECT id, user_id, source_item_id, quote_item_id, exact, prefix, suffix, offset_hint, created_at FROM highlights WHERE user_id = $1 AND source_item_id = $2 ORDER BY created_at ASC
`

type ListHighlightsBySourceParams struct {
	UserID       uuid.UUID
	SourceItemID uuid.UUID
}

func (q *Queries) ListHighlightsBySource(ctx context.Context, arg ListHighlightsBySourceParams) ([]Highlight, error) {
	rows, err := q.db.Query(ctx, listHighlightsBySource, arg.UserID, arg.SourceItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceItemID,
			&i.QuoteItemID,
			&i.Exact,
			&i.Prefix,
			&i.Suffix,
			&i.OffsetHint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
