// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotifications = `-- name: ClaimNotifications :exec
UPDATE notifications SET attempts = attempts + 1
WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type ClaimNotificationsParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) error {
	_, err := q.db.Exec(ctx, claimNotifications, arg.UserID, arg.Ids)
	return err
}

const countDeliveriesSince = `-- name: CountDeliveriesSince :one
SELECT count(DISTINCT nd.notification_id) FROM notification_deliveries nd
JOIN notifications n ON n.id = nd.notification_id
WHERE nd.user_id = $1 AND nd.ok AND nd.sent_at >= $2 AND n.category <> 'lifecycle'
`

type CountDeliveriesSinceParams struct {
	UserID uuid.UUID
	SentAt pgtype.Timestamptz
}

// Counts distinct outbox rows, not ledger rows, so the cap is independent of
// how many devices or channels a message fanned out to — a two-device
// push+email send would otherwise burn up to four units of budget for one
// notification. Joins notifications to exclude category = 'lifecycle':
// lifecycle bypasses the cap for itself, but without this predicate its
// deliveries would still count against everyone else's budget (ten
// lifecycle notifications at 09:00 would zero out the day's digest/feed_river
// allowance by 09:01).
func (q *Queries) CountDeliveriesSince(ctx context.Context, arg CountDeliveriesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveriesSince, arg.UserID, arg.SentAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deferNotifications = `-- name: DeferNotifications :exec
UPDATE notifications SET deliver_after = $2
WHERE user_id = $1 AND id = ANY($3::uuid[])
`

type DeferNotificationsParams struct {
	UserID       uuid.UUID
	DeliverAfter pgtype.Timestamptz
	Ids          []uuid.UUID
}

func (q *Queries) DeferNotifications(ctx context.Context, arg DeferNotificationsParams) error {
	_, err := q.db.Exec(ctx, deferNotifications, arg.UserID, arg.DeliverAfter, arg.Ids)
	return err
}

const deletePushDevice = `-- name: DeletePushDevice :execrows
DELETE FROM push_devices WHERE user_id = $1 AND token = $2
`

type DeletePushDeviceParams struct {
	UserID uuid.UUID
	Token  string
}

func (q *Queries) DeletePushDevice(ctx context.Context, arg DeletePushDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDevice, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notifications (user_id, category, dedupe_key, title, body, data)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, dedupe_key) WHERE sent_at IS NULL DO NOTHING
`

type EnqueueNotificationParams struct {
	UserID    uuid.UUID
	Category  string
	DedupeKey string
	Title     string
	Body      string
	Data      []byte
}

// ON CONFLICT DO NOTHING is the idempotency guard: the partial unique index
// covers pending rows only, so a producer re-run collapses into the existing
// row rather than duplicating, while a fresh window still gets its own row.
//
// deliver_after is deliberately omitted so the column DEFAULT now() applies.
// Listing it as a parameter would make sqlc generate a required field, and a
// caller leaving it zero would send an explicit NULL — which a DEFAULT does
// not rescue, because DEFAULT only fires for columns absent from the INSERT.
// Deferral (quiet hours, cap) happens later via DeferNotifications.
func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.UserID,
		arg.Category,
		arg.DedupeKey,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	return err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT email FROM users WHERE id = $1
`

// The flush job needs the account e-mail to resolve the e-mail channel's
// target. Scoped by id, which is the caller's own user_id.
func (q *Queries) GetUserEmail(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmail, id)
	var email string
	err := row.Scan(&email)
	return email, err
}

const listDueNotifications = `-- name: ListDueNotifications :many
SELECT id, category, dedupe_key, title, body, data
FROM notifications
WHERE user_id = $1 AND sent_at IS NULL AND attempts < 3 AND deliver_after <= now()
ORDER BY created_at
`

type ListDueNotificationsRow struct {
	ID        uuid.UUID
	Category  string
	DedupeKey string
	Title     string
	Body      string
	Data      []byte
}

func (q *Queries) ListDueNotifications(ctx context.Context, userID uuid.UUID) ([]ListDueNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listDueNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueNotificationsRow
	for rows.Next() {
		var i ListDueNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.DedupeKey,
			&i.Title,
			&i.Body,
			&i.Data,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushDevices = `-- name: ListPushDevices :many
SELECT token, platform FROM push_devices
WHERE user_id = $1 AND failed_at IS NULL
`

type ListPushDevicesRow struct {
	Token    string
	Platform string
}

func (q *Queries) ListPushDevices(ctx context.Context, userID uuid.UUID) ([]ListPushDevicesRow, error) {
	rows, err := q.db.Query(ctx, listPushDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushDevicesRow
	for rows.Next() {
		var i ListPushDevicesRow
		if err := rows.Scan(&i.Token, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTickets = `-- name: ListRecentTickets :many
SELECT DISTINCT ticket_id, token FROM notification_deliveries
WHERE channel = 'expo' AND ok AND ticket_id <> '' AND token <> ''
  AND sent_at > now() - interval '1 hour'
LIMIT 5000
`

type ListRecentTicketsRow struct {
	TicketID string
	Token    string
}

// The receipt job needs the token, not just the ticket, so it can retire a
// device Expo reports as unregistered. DISTINCT matters here: deliverOne
// writes one ledger row per (result x source row), so a single coalesced
// feed-river message covering several source rows on the same device writes
// several ledger rows for one ticket_id — without DISTINCT that duplication
// alone could push the row count past Expo's per-request cap well below any
// realistic push volume. LIMIT bounds the work done per run on a busy
// instance; the receipts job runs every 15 minutes, so a bounded backlog
// drains within a few cycles rather than growing unboundedly in one query.
//
// Deliberately unscoped: this is global periodic maintenance across every
// user's outbox, not a per-user read, so a user_id predicate would defeat it
// the same way it would for ListUsersWithDueNotifications.
func (q *Queries) ListRecentTickets(ctx context.Context) ([]ListRecentTicketsRow, error) {
	rows, err := q.db.Query(ctx, listRecentTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTicketsRow
	for rows.Next() {
		var i ListRecentTicketsRow
		if err := rows.Scan(&i.TicketID, &i.Token); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithDueNotifications = `-- name: ListUsersWithDueNotifications :many
SELECT DISTINCT user_id FROM notifications
WHERE sent_at IS NULL AND attempts < 3 AND deliver_after <= now()
`

// Deliberately unscoped: the flush job's whole purpose is to enumerate every
// user with due work, so a user_id predicate would defeat it.
func (q *Queries) ListUsersWithDueNotifications(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWithDueNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsFailed = `-- name: MarkNotificationsFailed :exec
UPDATE notifications SET last_error = $2
WHERE user_id = $1 AND id = ANY($3::uuid[])
`

type MarkNotificationsFailedParams struct {
	UserID    uuid.UUID
	LastError string
	Ids       []uuid.UUID
}

func (q *Queries) MarkNotificationsFailed(ctx context.Context, arg MarkNotificationsFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationsFailed, arg.UserID, arg.LastError, arg.Ids)
	return err
}

const markNotificationsSent = `-- name: MarkNotificationsSent :exec
UPDATE notifications SET sent_at = now(), last_error = ''
WHERE user_id = $1 AND id = ANY($2::uuid[])
`

type MarkNotificationsSentParams struct {
	UserID uuid.UUID
	Ids    []uuid.UUID
}

func (q *Queries) MarkNotificationsSent(ctx context.Context, arg MarkNotificationsSentParams) error {
	_, err := q.db.Exec(ctx, markNotificationsSent, arg.UserID, arg.Ids)
	return err
}

const markPushDeviceFailed = `-- name: MarkPushDeviceFailed :exec
UPDATE push_devices SET failed_at = now() WHERE token = $1
`

// Deliberately unscoped: token is UNIQUE, so it alone identifies exactly one
// row and a user_id predicate would be redundant.
func (q *Queries) MarkPushDeviceFailed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPushDeviceFailed, token)
	return err
}

const pruneNotifications = `-- name: PruneNotifications :execrows
DELETE FROM notifications
WHERE (sent_at IS NOT NULL AND sent_at < now() - interval '30 days')
   OR (sent_at IS NULL AND attempts >= 3 AND created_at < now() - interval '7 days')
   OR (sent_at IS NULL AND created_at < now() - interval '30 days')
`

// Three clauses: delivered rows age out after 30 days; abandoned rows
// (retries exhausted, never sent) after 7; and any other still-pending row
// after 30 days regardless of attempts — e.g. one kept deferred because the
// user never registers a push device or e-mail, so it is never claimed and
// never exhausts attempts on its own. Without this third clause such a row
// would sit in the pending partial index forever.
//
// Deliberately unscoped: retention is global periodic maintenance over the
// whole outbox, not a per-user operation, so a user_id predicate would defeat
// it the same way it would for ListUsersWithDueNotifications.
func (q *Queries) PruneNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordDelivery = `-- name: RecordDelivery :exec
INSERT INTO notification_deliveries (user_id, notification_id, channel, token, ticket_id, ok, error)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordDeliveryParams struct {
	UserID         uuid.UUID
	NotificationID uuid.UUID
	Channel        string
	Token          string
	TicketID       string
	Ok             bool
	Error          string
}

func (q *Queries) RecordDelivery(ctx context.Context, arg RecordDeliveryParams) error {
	_, err := q.db.Exec(ctx, recordDelivery,
		arg.UserID,
		arg.NotificationID,
		arg.Channel,
		arg.Token,
		arg.TicketID,
		arg.Ok,
		arg.Error,
	)
	return err
}

const upsertPushDevice = `-- name: UpsertPushDevice :execrows
INSERT INTO push_devices (user_id, api_key_id, token, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE
SET api_key_id = EXCLUDED.api_key_id,
    platform = EXCLUDED.platform,
    last_seen_at = now(),
    failed_at = NULL
WHERE push_devices.user_id = EXCLUDED.user_id
`

type UpsertPushDeviceParams struct {
	UserID   uuid.UUID
	ApiKeyID pgtype.UUID
	Token    string
	Platform string
}

// The conflict target is token alone, so without a guard any authenticated
// user who knew (or guessed, or had leaked to them) another user's Expo token
// could claim it: the update would reassign user_id, silently stealing the
// victim's device — the victim stops receiving their own notifications and
// starts receiving the attacker's instead. user_id is therefore left out of
// the SET list entirely (ownership never transfers on conflict), and the
// WHERE clause makes a cross-user conflict affect zero rows instead of
// succeeding. :execrows lets the caller distinguish that zero-row outcome
// from a real insert or same-user update.
//
// The Expo push token is per-install, not per-account, so a genuine account
// switch on one device relies on the outgoing client releasing its own
// token first — mobile does this in settings-context.tsx, both ahead of
// clearing its stored credentials on sign-out and ahead of overwriting them
// when save() detects the credentials being saved belong to a different
// account than what's currently stored (e.g. connecting with a new code
// without tapping sign-out first). There is no automatic cascade to fall
// back on for the mobile case: mobile always trades its Clerk session or
// device code for an omk_ API key, so its rows carry a non-NULL
// api_key_id, but a normal sign-out never revokes that key (see
// pushdevices.go's RegisterPushDevice comment) — so nothing cascades the row
// away just because the account signed out. Clerk and dev-mode callers are a
// separate, secondary case: push_devices.api_key_id is only populated for
// API-key callers, so those rows (api_key_id NULL) have no key to cascade
// from regardless of how sign-out happens.
//
// What's still uncovered after mobile's release call: a release that fails
// in flight (offline, instance unreachable) or a crash between the
// credential change and the release running. Either leaves the row owned by
// the previous account, and the WHERE clause turns the next account's
// registration attempt into a no-op 409 instead of a silent takeover — but
// recovering from that state is still manual (an operator deletes or
// reassigns the row).
func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPushDevice,
		arg.UserID,
		arg.ApiKeyID,
		arg.Token,
		arg.Platform,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
