// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: places.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteItemPlaces = `-- name: DeleteItemPlaces :exec
DELETE FROM item_places WHERE user_id = $1 AND item_id = $2
`

type DeleteItemPlacesParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) DeleteItemPlaces(ctx context.Context, arg DeleteItemPlacesParams) error {
	_, err := q.db.Exec(ctx, deleteItemPlaces, arg.UserID, arg.ItemID)
	return err
}

const insertItemPlace = `-- name: InsertItemPlace :exec
INSERT INTO item_places (user_id, item_id, name, hint, address, lat, lng, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertItemPlaceParams struct {
	UserID  uuid.UUID
	ItemID  uuid.UUID
	Name    string
	Hint    string
	Address string
	Lat     pgtype.Float8
	Lng     pgtype.Float8
	Source  string
}

func (q *Queries) InsertItemPlace(ctx context.Context, arg InsertItemPlaceParams) error {
	_, err := q.db.Exec(ctx, insertItemPlace,
		arg.UserID,
		arg.ItemID,
		arg.Name,
		arg.Hint,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.Source,
	)
	return err
}

const listItemPlaces = `-- name: ListItemPlaces :many
SELECT id, user_id, item_id, name, hint, address, lat, lng, source, created_at FROM item_places WHERE user_id = $1 AND item_id = $2 ORDER BY created_at, name
`

type ListItemPlacesParams struct {
	UserID uuid.UUID
	ItemID uuid.UUID
}

func (q *Queries) ListItemPlaces(ctx context.Context, arg ListItemPlacesParams) ([]ItemPlace, error) {
	rows, err := q.db.Query(ctx, listItemPlaces, arg.UserID, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemPlace
	for rows.Next() {
		var i ItemPlace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.Name,
			&i.Hint,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
